### ISSUE TITLE
Cannot add DP to variant fields

### ISSUE THREAD

**Issue by brankovicmarija** [vatlab/VariantTools#103]
Hello!
I am using version 3.0.2 trying to add DP to the available fields according to your tutorial with the following command:

`vtools import ././SCN198.selected.vcf --build hg19 --var_info DP,qual,filter,id --geno_info DP_geno,AD_geno,qual --format vcf`

First I get an unusual warning:
`WARNING: hg19: Failed to get reference sequence: unrecognized chromosome id: 65535`
There is no such sequence in my file:
$grep 65535 SCN198.selected.vcf 
`chr12	82265535	.	A	G	35.44	PASS	AC=2;AF=1.00;AN=2;DP=1;ExcessHet=3.0103;FS=0.000;MLEAC=1;MLEAF=0.500;MQ=60.00;QD=32.33;SOR=1.609GT:AD:DP:GQ:PL	1/1:0,1:1:3:45,3,0`

Then, I get an error:
```
Importing genotypes: 100% [=================================================================================================] 531,172 37.9K/s in 00:00:14
Copying samples: 100% [=============================================================================================================] 1 0.2/s in 00:00:04
Current storage mode is HDF5, transfrom genotype storage mode.....
Creating indexes: 100% [============================================================================================================] 1 0.8/s in 00:00:01
Selecting genotypes: 100% [=========================================================================================================] 2 2.0/s in 00:00:01
Getting existing variants: 100% [==========================================================================================] 265,963 640.5K/s in 00:00:00
list index out of range
Process GenotypeImporter:
Traceback (most recent call last):
  File "/home/korisnik/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/korisnik/anaconda3/lib/python3.7/site-packages/variant_tools/importer_allele_hdf5.py", line 1135, in run
    self.get_geno(variant_id,i,altIndex)
  File "/home/korisnik/anaconda3/lib/python3.7/site-packages/variant_tools/importer_allele_hdf5.py", line 1078, in get_geno
    if "variants" in self.namedict[info]:
KeyError: 'DP'
```
Even though the process fails, the sample is still added to the list:
```
vtools show samples
test20     	SCN198.selected.vcf
test20     	./eff.scn198.vcf
test20     	./SCN198.selected.vcf
test20     	eff.scn198.vcf
```

When I try to remove the samples to try importing again, it fails:
```
$ vtools remove samples '*'
ERROR: Failed to retrieve samples by condition "(*)": near "*": syntax error
$ vtools remove samples 'filename = SCN198.selected.vcf'
ERROR: Failed to retrieve samples by condition "(filename = SCN198.selected.vcf)": no such column: SCN198.selected.vcf
```

Is there a systematic error here I am not seeing? How can I remove the sample and add DP to my fields?

**Comment by jma7** [comment]
Hi brankovicmarija,
  Would you please remove the ```--format vcf```, just try
```
vtools import ././SCN198.selected.vcf --build hg19 --var_info DP,qual,filter,id --geno_info DP_geno,AD_geno,qual
```
Since your file is in vcf format which is the default format.

**Comment by brankovicmarija** [comment]
Hi!
I tried that but it returns this message: [:10])>0:
TypeError: '>' not supported between instances of 'str' and 'int'
Also tried this command grep ">0" eff.scn198.vcf and nothing found

**Comment by jma7** [comment]
Have you tried reinitiate the project from the beginning?
```
vtools init myproject -f
```
Then, import vcf again.

**Comment by BoPeng** [comment]
@brankovicmarija Could you send us a minimal example to demonstrate the problem, such as the first 1000 lines of your vcf file and exact commands that you have used?

**Comment by brankovicmarija** [comment]
@jma7 I tried but it is the same error :[:10])>0:
TypeError: '>' not supported between instances of 'str' and 'int'

@BoPeng Here is the command: vtools import ./SCN198.selected.vcf --build hg19 --var_info DP,qual,filter,id --geno_info DP_geno,AD_geno,qual
And here is the vcf: ##fileformat=VCFv4.2
##FILTER=<ID=LowQual,Description="Low quality">
##FILTER=<ID=my-indel_filter,Description="QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0 || SOR > 10.0">
##FILTER=<ID=my_snp_filter,Description="QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0 || SOR > 3.0">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
##GATKCommandLine=<ID=HaplotypeCaller,CommandLine="HaplotypeCaller Version=4.1.0.0,Date="March 1, 2019 3:18:49 PM CET">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=BaseQRankSum,Number=1,Type=Float,Description="Z-score from Wilcoxon rank sum test of Alt Vs. Ref base qualities">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth; some reads may have been filtered">
##INFO=<ID=DS,Number=0,Type=Flag,Description="Were any of the samples downsampled?">
##INFO=<ID=ExcessHet,Number=1,Type=Float,Description="Phred-scaled p-value for exact test of excess heterozygosity">
##INFO=<ID=FS,Number=1,Type=Float,Description="Phred-scaled p-value using Fisher's exact test to detect strand bias">
##INFO=<ID=InbreedingCoeff,Number=1,Type=Float,Description="Inbreeding coefficient as estimated from the genotype likelihoods per-sample when compared against the Hardy-Weinberg expectation">
##INFO=<ID=MLEAC,Number=A,Type=Integer,Description="Maximum likelihood expectation (MLE) for the allele counts (not necessarily the same as the AC), for each ALT allele, in the same order as listed">
##INFO=<ID=MLEAF,Number=A,Type=Float,Description="Maximum likelihood expectation (MLE) for the allele frequency (not necessarily the same as the AF), for each ALT allele, in the same order as listed">
##INFO=<ID=MQ,Number=1,Type=Float,Description="RMS Mapping Quality">
##INFO=<ID=MQRankSum,Number=1,Type=Float,Description="Z-score From Wilcoxon rank sum test of Alt vs. Ref read mapping qualities">
##INFO=<ID=QD,Number=1,Type=Float,Description="Variant Confidence/Quality by Depth">
##INFO=<ID=ReadPosRankSum,Number=1,Type=Float,Description="Z-score from Wilcoxon rank sum test of Alt vs. Ref read position bias">
##INFO=<ID=SOR,Number=1,Type=Float,Description="Symmetric Odds Ratio of 2x2 contingency table to detect strand bias">
##contig=<ID=chr10,length=135534747,assembly=wg.fa>
##contig=<ID=chr11,length=135006516,assembly=wg.fa>
##contig=<ID=chr11_gl000202_random,length=40103,assembly=wg.fa>
##contig=<ID=chr12,length=133851895,assembly=wg.fa>
##contig=<ID=chr13,length=115169878,assembly=wg.fa>
##contig=<ID=chr14,length=107349540,assembly=wg.fa>
##contig=<ID=chr15,length=102531392,assembly=wg.fa>
##contig=<ID=chr16,length=90354753,assembly=wg.fa>
##contig=<ID=chr17_ctg5_hap1,length=1680828,assembly=wg.fa>
##contig=<ID=chr17,length=81195210,assembly=wg.fa>
##contig=<ID=chr17_gl000203_random,length=37498,assembly=wg.fa>
##contig=<ID=chr17_gl000204_random,length=81310,assembly=wg.fa>
##contig=<ID=chr17_gl000205_random,length=174588,assembly=wg.fa>
##contig=<ID=chr17_gl000206_random,length=41001,assembly=wg.fa>
##contig=<ID=chr18,length=78077248,assembly=wg.fa>
##contig=<ID=chr18_gl000207_random,length=4262,assembly=wg.fa>
##contig=<ID=chr19,length=59128983,assembly=wg.fa>
##contig=<ID=chr19_gl000208_random,length=92689,assembly=wg.fa>
##contig=<ID=chr19_gl000209_random,length=159169,assembly=wg.fa>
##contig=<ID=chr1,length=249250621,assembly=wg.fa>
##contig=<ID=chr1_gl000191_random,length=106433,assembly=wg.fa>
##contig=<ID=chr1_gl000192_random,length=547496,assembly=wg.fa>
##contig=<ID=chr20,length=63025520,assembly=wg.fa>
##contig=<ID=chr21,length=48129895,assembly=wg.fa>
##contig=<ID=chr21_gl000210_random,length=27682,assembly=wg.fa>
##contig=<ID=chr22,length=51304566,assembly=wg.fa>
##contig=<ID=chr2,length=243199373,assembly=wg.fa>
##contig=<ID=chr3,length=198022430,assembly=wg.fa>
##contig=<ID=chr4_ctg9_hap1,length=590426,assembly=wg.fa>
##contig=<ID=chr4,length=191154276,assembly=wg.fa>
##contig=<ID=chr4_gl000193_random,length=189789,assembly=wg.fa>
##contig=<ID=chr4_gl000194_random,length=191469,assembly=wg.fa>
##contig=<ID=chr5,length=180915260,assembly=wg.fa>
##contig=<ID=chr6_apd_hap1,length=4622290,assembly=wg.fa>
##contig=<ID=chr6_cox_hap2,length=4795371,assembly=wg.fa>
##contig=<ID=chr6_dbb_hap3,length=4610396,assembly=wg.fa>
##contig=<ID=chr6,length=171115067,assembly=wg.fa>
##contig=<ID=chr6_mann_hap4,length=4683263,assembly=wg.fa>
##contig=<ID=chr6_mcf_hap5,length=4833398,assembly=wg.fa>
##contig=<ID=chr6_qbl_hap6,length=4611984,assembly=wg.fa>
##contig=<ID=chr6_ssto_hap7,length=4928567,assembly=wg.fa>
##contig=<ID=chr7,length=159138663,assembly=wg.fa>
##contig=<ID=chr7_gl000195_random,length=182896,assembly=wg.fa>
##contig=<ID=chr8,length=146364022,assembly=wg.fa>
##contig=<ID=chr8_gl000196_random,length=38914,assembly=wg.fa>
##contig=<ID=chr8_gl000197_random,length=37175,assembly=wg.fa>
##contig=<ID=chr9,length=141213431,assembly=wg.fa>
##contig=<ID=chr9_gl000198_random,length=90085,assembly=wg.fa>
##contig=<ID=chr9_gl000199_random,length=169874,assembly=wg.fa>
##contig=<ID=chr9_gl000200_random,length=187035,assembly=wg.fa>
##contig=<ID=chr9_gl000201_random,length=36148,assembly=wg.fa>
##contig=<ID=chrM,length=16571,assembly=wg.fa>
##contig=<ID=chrUn_gl000211,length=166566,assembly=wg.fa>
##contig=<ID=chrUn_gl000212,length=186858,assembly=wg.fa>
##contig=<ID=chrUn_gl000213,length=164239,assembly=wg.fa>
##contig=<ID=chrUn_gl000214,length=137718,assembly=wg.fa>
##contig=<ID=chrUn_gl000215,length=172545,assembly=wg.fa>
##contig=<ID=chrUn_gl000216,length=172294,assembly=wg.fa>
##contig=<ID=chrUn_gl000217,length=172149,assembly=wg.fa>
##contig=<ID=chrUn_gl000218,length=161147,assembly=wg.fa>
##contig=<ID=chrUn_gl000219,length=179198,assembly=wg.fa>
##contig=<ID=chrUn_gl000220,length=161802,assembly=wg.fa>
##contig=<ID=chrUn_gl000221,length=155397,assembly=wg.fa>
##contig=<ID=chrUn_gl000222,length=186861,assembly=wg.fa>
##contig=<ID=chrUn_gl000223,length=180455,assembly=wg.fa>
##contig=<ID=chrUn_gl000224,length=179693,assembly=wg.fa>
##contig=<ID=chrUn_gl000225,length=211173,assembly=wg.fa>
##contig=<ID=chrUn_gl000226,length=15008,assembly=wg.fa>
##contig=<ID=chrUn_gl000227,length=128374,assembly=wg.fa>
##contig=<ID=chrUn_gl000228,length=129120,assembly=wg.fa>
##contig=<ID=chrUn_gl000229,length=19913,assembly=wg.fa>
##contig=<ID=chrUn_gl000230,length=43691,assembly=wg.fa>
##contig=<ID=chrUn_gl000231,length=27386,assembly=wg.fa>
##contig=<ID=chrUn_gl000232,length=40652,assembly=wg.fa>
##contig=<ID=chrUn_gl000233,length=45941,assembly=wg.fa>
##contig=<ID=chrUn_gl000234,length=40531,assembly=wg.fa>
##contig=<ID=chrUn_gl000235,length=34474,assembly=wg.fa>
##contig=<ID=chrUn_gl000236,length=41934,assembly=wg.fa>
##contig=<ID=chrUn_gl000237,length=45867,assembly=wg.fa>
##contig=<ID=chrUn_gl000238,length=39939,assembly=wg.fa>
##contig=<ID=chrUn_gl000239,length=33824,assembly=wg.fa>
##contig=<ID=chrUn_gl000240,length=41933,assembly=wg.fa>
##contig=<ID=chrUn_gl000241,length=42152,assembly=wg.fa>
##contig=<ID=chrUn_gl000242,length=43523,assembly=wg.fa>
##contig=<ID=chrUn_gl000243,length=43341,assembly=wg.fa>
##contig=<ID=chrUn_gl000244,length=39929,assembly=wg.fa>
##contig=<ID=chrUn_gl000245,length=36651,assembly=wg.fa>
##contig=<ID=chrUn_gl000246,length=38154,assembly=wg.fa>
##contig=<ID=chrUn_gl000247,length=36422,assembly=wg.fa>
##contig=<ID=chrUn_gl000248,length=39786,assembly=wg.fa>
##contig=<ID=chrUn_gl000249,length=38502,assembly=wg.fa>
##contig=<ID=chrX,length=155270560,assembly=wg.fa>
##contig=<ID=chrY,length=59373566,assembly=wg.fa>
##reference=file:///home/korisnik/Downloads/wg.fa
##source=HaplotypeCaller
##source=SelectVariants
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	test20
chr10	64863	.	A	C	37.28	my_snp_filter	AC=2;AF=1.00;AN=2;DP=2;ExcessHet=3.0103;FS=0.000;MLEAC=1;MLEAF=0.500;MQ=27.00;QD=18.64;SOR=0.693	GT:AD:DP:GQ:PL	1/1:0,2:2:6:49,6,0
chr10	64863	.	A	C	37.28	PASS	AC=2;AF=1.00;AN=2;DP=2;ExcessHet=3.0103;FS=0.000;MLEAC=1;MLEAF=0.500;MQ=27.00;QD=18.64;SOR=0.693	GT:AD:DP:GQ:PL	1/1:0,2:2:6:49,6,0
chr10	68091	.	T	C	37.28	PASS	AC=2;AF=1.00;AN=2;DP=2;ExcessHet=3.0103;FS=0.000;MLEAC=1;MLEAF=0.500;MQ=60.00;QD=18.64;SOR=0.693	GT:AD:DP:GQ:PL	1/1:0,2:2:6:49,6,0
chr10	68091	.	T	C	37.28	PASS	AC=2;AF=1.00;AN=2;DP=2;ExcessHet=3.0103;FS=0.000;MLEAC=1;MLEAF=0.500;MQ=60.00;QD=18.64;SOR=0.693	GT:AD:DP:GQ:PL	1/1:0,2:2:6:49,6,0
chr10	74448	.	G	T	37.28	PASS	AC=2;AF=1.00;AN=2;DP=2;ExcessHet=3.0103;FS=0.000;MLEAC=1;MLEAF=0.500;MQ=47.00;QD=18.64;SOR=0.693	GT:AD:DP:GQ:PL	1/1:0,2:2:6:49,6,0
chr10	74448	.	G	T	37.28	PASS	AC=2;AF=1.00;AN=2;DP=2;ExcessHet=3.0103;FS=0.000;MLEAC=1;MLEAF=0.500;MQ=47.00;QD=18.64;SOR=0.693	GT:AD:DP:GQ:PL	1/1:0,2:2:6:49,6,0
chr10	93603	.	C	T	143.10	my_snp_filter	AC=2;AF=1.00;AN=2;DP=4;ExcessHet=3.0103;FS=0.000;MLEAC=2;MLEAF=1.00;MQ=37.18;QD=25.36;SOR=1.609	GT:AD:DP:GQ:PL	1/1:0,4:4:12:157,12,0
chr10	93603	.	C	T	143.10	PASS	AC=2;AF=1.00;AN=2;DP=4;ExcessHet=3.0103;FS=0.000;MLEAC=2;MLEAF=1.00;MQ=37.18;QD=25.36;SOR=1.609	GT:AD:DP:GQ:PL	1/1:0,4:4:12:157,12,0
chr10	93816	.	C	T	362.60	PASS	AC=1;AF=0.500;AN=2;BaseQRankSum=-1.030;DP=21;ExcessHet=3.0103;FS=0.000;MLEAC=1;MLEAF=0.500;MQ=58.85;MQRankSum=-0.686;QD=17.27;ReadPosRankSum=-0.943;SOR=0.458	GT:AD:DP:GQ:PL	0/1:8,13:21:99:370,0,242
chr10	93816	.	C	T	362.60	PASS	AC=1;AF=0.500;AN=2;BaseQRankSum=-1.030;DP=21;ExcessHet=3.0103;FS=0.000;MLEAC=1;MLEAF=0.500;MQ=58.85;MQRankSum=-0.686;QD=17.27;ReadPosRankSum=-0.943;SOR=0.458	GT:AD:DP:GQ:PL	0/1:8,13:21:99:370,0,242
chr10	93945	.	G	A	278.98	PASS	AC=2;AF=1.00;AN=2;DP=7;ExcessHet=3.0103;FS=0.000;MLEAC=2;MLEAF=1.00;MQ=54.81;QD=28.73;SOR=4.174	GT:AD:DP:GQ:PL	1/1:0,7:7:21:293,21,0
chr10	93945	.	G	A	278.98	PASS	AC=2;AF=1.00;AN=2;DP=7;ExcessHet=3.0103;FS=0.000;MLEAC=2;MLEAF=1.00;MQ=54.81;QD=28.73;SOR=4.174	GT:AD:DP:GQ:PL	1/1:0,7:7:21:293,21,0
chr10	94083	.	C	T	33.44	PASS	AC=2;AF=1.00;AN=2;DP=1;ExcessHet=3.0103;FS=0.000;MLEAC=1;MLEAF=0.500;MQ=40.00;QD=33.44;SOR=1.609	GT:AD:DP:GQ:PL	1/1:0,1:1:3:43,3,0
chr10	94083	.	C	T	33.44	PASS	AC=2;AF=1.00;AN=2;DP=1;ExcessHet=3.0103;FS=0.000;MLEAC=1;MLEAF=0.500;MQ=40.00;QD=33.44;SOR=1.609	GT:AD:DP:GQ:PL	1/1:0,1:1:3:43,3,0
chr10	95226	.	A	T	67.28	PASS	AC=2;AF=1.00;AN=2;DP=2;ExcessHet=3.0103;FS=0.000;MLEAC=1;MLEAF=0.500;MQ=60.00;QD=33.64;SOR=0.693	GT:AD:DP:GQ:PL	1/1:0,2:2:6:79,6,0

**Comment by jma7** [comment]
Hi,
   The ```--var_info``` option in the ```vtools import``` command line was meant to import fields in the ```INFO``` column from the vcf file, currently ```DP,GQ,GD,HQ,AD,PL,MQ,NS``` tags are supported.
So you might want to adjust your command line to include the tags you are interested in, for example
```
vtools import SCN198.selected.vcf --build hg19 --var_info DP AC AF --geno_info DP_geno,AD_geno
```
We will improve our error reporting to make this more clear, Thanks!

**Comment by brankovicmarija** [comment]
Thanks for the reply. 

We reset the project and tried your command. There were many non-breaking key errors during the execution e.g.:

```
Traceback (most recent call last):
  File "/home/korisnik/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/korisnik/anaconda3/lib/python3.7/site-packages/variant_tools/importer_allele_hdf5.py", line 1132, in run
    variant_id  = self.variantIndex[tuple((chr, ref, alt))][pos][0]
KeyError: 110874502
```

Looking at the VCF file there were always locations one position smaller. I also remind you of my first post and the problem with warning "unrecognized chromosome id: 65535".

At the end, we show fields:
```
variant.chr (char)      Chromosome name (VARCHAR)
variant.pos (int)       Position (INT, 1-based)
variant.ref (char)      Reference allele (VARCHAR, - for missing allele of an
                        insertion)
variant.alt (char)      Alternative allele (VARCHAR, - for missing allele of an
                        deletion)
variant.DP (int)
variant.AC (int)
variant.AF (float)
variant.num (int)       Created from stat "#(alt)"  with type INT on Apr19
variant.hom (int)       Created from stat "#(hom)"  with type INT on Apr19
variant.het (int)       Created from stat "#(het)"  with type INT on Apr19
variant.other (int)     Created from stat "#(other)"  with type INT on Apr19
variant.total (int)     Created from stat "#(GT)"  with type INT on Apr19
```

Any clue why DP_geno was not generated?

Thanks!

**Comment by jma7** [comment]
```vtools show fields``` will only show the fields in the variant table. DP_geno is for each sample which is saved in *.h5 file.  I am not sure what is causing the one position smaller problem you mentioned. It seems that there are duplication of variants in your VCF file, but the sample file was imported fine at my end. Would you please send me the portion of the VCF file having the key error problem, maybe plus minus 100 lines around position ```110874502```?
