### ISSUE TITLE
Associate analysis error in the test for hdf5

### ISSUE THREAD

**Issue by HenryLeongStat** [vatlab/VariantTools#49]
I was trying to run the associate test but the error showed up...

**Note: the error only shows up on Linux server, it doesn't show up on my laptop.**

```
mleong@q1prpfs04:~/j6htestVarianttools$  vtools associate variant smoking --discard_variants "%(NA)>0.1" --HDF --method "BurdenBt --name BurdenTest --alternative 2" --group_by refGene.name2  -j 6 --force -v 2
DEBUG:
DEBUG: associate variant smoking --discard_variants %(NA)>0.1 --HDF --method "BurdenBt --name BurdenTest --alternative 2" --group_by refGene.name2 -j 6 --force -v 2
DEBUG: Using temporary directory /tmp/tmpsd5fksxl/_tmp_149688
DEBUG: Select phenotype and covariates using query SELECT sample_id, sample_name, smoking FROM sample LEFT OUTER JOIN filename ON sample.file_id = filename.file_id WHERE smoking IS NOT NULL
INFO: 2504 samples are found
DEBUG: Running query INSERT INTO __asso_tmp SELECT DISTINCT variant.variant_id, 0, refGene.refGene.name2  FROM variant, refGene.__rng_refGene_hg19_chr_txStart_txEnd, refGene.refGene WHERE (variant.bin = refGene.__rng_refGene_hg19_chr_txStart_txEnd.bin AND variant.chr = refGene.__rng_refGene_hg19_chr_txStart_txEnd.chr AND variant.pos >= refGene.__rng_refGene_hg19_chr_txStart_txEnd.start AND variant.pos <= refGene.__rng_refGene_hg19_chr_txStart_txEnd.end ) AND (refGene.refGene.rowid = refGene.__rng_refGene_hg19_chr_txStart_txEnd.range_id);
INFO: Grouping variants by 'refGene.name2', please be patient ...
INFO: 573 groups are found
Process GroupHDFGenerator-5:
Traceback (most recent call last):
  File "/home/mleong/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association_hdf5.py", line 77, in run
    for row in cur.execute(select_group):
vt_sqlite3.OperationalError: unable to open database file

('group time: ', 69.71390271186829)
Testing for association:   0.0% [>                                                                                                                                    ]  in 00:00:00Process Phenotype association analysis for a group of variants:
Traceback (most recent call last):
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association.py", line 972, in run
    genotype, which, var_info, geno_info = getGenotype_HDF5(self,grp)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association_hdf5.py", line 347, in getGenotype_HDF5
    colnames=accessEngine.get_colnames(chr,geneSymbol)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/accessor.py", line 1155, in get_colnames
    return group.colnames[:]
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/tables/group.py", line 818, in __getattr__
    return self._f_get_child(name)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/tables/group.py", line 698, in _f_get_child
    self._g_check_has_child(childname)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/tables/group.py", line 395, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/chr22/ADM2`` does not have a child named ``colnames``

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mleong/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association.py", line 993, in run
    except Exception as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
Process Phenotype association analysis for a group of variants:
Traceback (most recent call last):
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association.py", line 972, in run
    genotype, which, var_info, geno_info = getGenotype_HDF5(self,grp)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association_hdf5.py", line 347, in getGenotype_HDF5
    colnames=accessEngine.get_colnames(chr,geneSymbol)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/accessor.py", line 1155, in get_colnames
    return group.colnames[:]
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/tables/group.py", line 818, in __getattr__
    return self._f_get_child(name)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/tables/group.py", line 698, in _f_get_child
    self._g_check_has_child(childname)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/tables/group.py", line 395, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/chr22/A4GALT`` does not have a child named ``colnames``

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mleong/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association.py", line 993, in run
    except Exception as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
Process Phenotype association analysis for a group of variants:
Traceback (most recent call last):
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association.py", line 972, in run
    genotype, which, var_info, geno_info = getGenotype_HDF5(self,grp)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association_hdf5.py", line 347, in getGenotype_HDF5
    colnames=accessEngine.get_colnames(chr,geneSymbol)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/accessor.py", line 1155, in get_colnames
    return group.colnames[:]
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/tables/group.py", line 818, in __getattr__
    return self._f_get_child(name)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/tables/group.py", line 698, in _f_get_child
    self._g_check_has_child(childname)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/tables/group.py", line 395, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/chr22/ACR`` does not have a child named ``colnames``

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mleong/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association.py", line 993, in run
    except Exception as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
Process Phenotype association analysis for a group of variants:
Traceback (most recent call last):
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association.py", line 972, in run
    genotype, which, var_info, geno_info = getGenotype_HDF5(self,grp)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association_hdf5.py", line 347, in getGenotype_HDF5
    colnames=accessEngine.get_colnames(chr,geneSymbol)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/accessor.py", line 1155, in get_colnames
    return group.colnames[:]
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/tables/group.py", line 818, in __getattr__
    return self._f_get_child(name)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/tables/group.py", line 698, in _f_get_child
    self._g_check_has_child(childname)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/tables/group.py", line 395, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/chr22/ADORA2A`` does not have a child named ``colnames``

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mleong/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association.py", line 993, in run
    except Exception as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
Process Phenotype association analysis for a group of variants:
Traceback (most recent call last):
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association.py", line 972, in run
    genotype, which, var_info, geno_info = getGenotype_HDF5(self,grp)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association_hdf5.py", line 347, in getGenotype_HDF5
    colnames=accessEngine.get_colnames(chr,geneSymbol)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/accessor.py", line 1155, in get_colnames
    return group.colnames[:]
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/tables/group.py", line 818, in __getattr__
    return self._f_get_child(name)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/tables/group.py", line 698, in _f_get_child
    self._g_check_has_child(childname)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/tables/group.py", line 395, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/chr22/ACO2`` does not have a child named ``colnames``

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mleong/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association.py", line 993, in run
    except Exception as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
Process Phenotype association analysis for a group of variants:
Traceback (most recent call last):
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association.py", line 972, in run
    genotype, which, var_info, geno_info = getGenotype_HDF5(self,grp)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association_hdf5.py", line 347, in getGenotype_HDF5
    colnames=accessEngine.get_colnames(chr,geneSymbol)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/accessor.py", line 1155, in get_colnames
    return group.colnames[:]
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/tables/group.py", line 818, in __getattr__
    return self._f_get_child(name)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/tables/group.py", line 698, in _f_get_child
    self._g_check_has_child(childname)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/tables/group.py", line 395, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/chr22/ADORA2A_AS1`` does not have a child named ``colnames``

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mleong/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association.py", line 993, in run
    except Exception as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
^CERROR:
Association tests stopped by keyboard interruption (0/573 completed).
refgene_name2	sample_size_BurdenTest	num_variants_BurdenTest	total_mac_BurdenTest	beta_x_BurdenTest	pvalue_BurdenTest	wald_x_BurdenTest
Traceback (most recent call last):
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association.py", line 1117, in runAssociation
    res = resQueue.get()
  File "/home/mleong/anaconda3/lib/python3.6/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/home/mleong/anaconda3/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/mleong/anaconda3/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/mleong/anaconda3/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association.py", line 1128, in runAssociation
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association.py", line 1226, in associate
    runAssociation(args,asso,proj,results)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association.py", line 1144, in runAssociation
    except Exception as e:
TypeError: catching classes that do not inherit from BaseException is not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mleong/anaconda3/bin/vtools", line 11, in <module>
    load_entry_point('variant-tools==3.0.0.dev0', 'console_scripts', 'vtools')()
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/vtools.py", line 266, in main
    args.func(args)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association.py", line 1228, in associate
    except Exception as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Comment by HenryLeongStat** [comment]
After I run the first time, I interrupt it by Ctrl + C and then try to run again in the same folder, it starts processing without error messages like the followings:

<img width="1265" alt="screen shot 2017-11-01 at 11 15 40 am" src="https://user-images.githubusercontent.com/26916551/32284691-05b83d02-bef6-11e7-9528-97fd807b7c1b.png">

**Comment by HenryLeongStat** [comment]
It works at the second times (after the error message showed up at the first time), and the result should be the same as the test at `sqlite`:

<img width="1183" alt="screen shot 2017-11-01 at 11 32 29 am" src="https://user-images.githubusercontent.com/26916551/32285527-8e84029a-bef8-11e7-9b8b-f5a1733bfb6e.png">

**Comment by HenryLeongStat** [comment]
According to the output, there are quite a lot of rows in the results are different between hdf5 and sqlite.

<img width="1086" alt="screen shot 2017-11-01 at 4 30 36 pm" src="https://user-images.githubusercontent.com/26916551/32299059-2feadf04-bf22-11e7-9a5c-16f4f7e5fd5a.png">

**Comment by gaow** [comment]
It looks like sql data has less variants than hdf5 -- perhaps hdf5 version did not implement the variant filters by missingness or something?

**Comment by HenryLeongStat** [comment]
Error messages still show up after I compile successfully on Linux server:

```
mleong@q1prpfs04:~/VariantTools/j10htestVarianttools$ vtools associate variant smoking --discard_variants "%(NA)>0.1" --HDF --method "BurdenBt --name BurdenTest --alternative 2" --group_by refGene.name2  -j 10 --force -v 2 > asso_test_j10_hdf5.log
DEBUG:
DEBUG: associate variant smoking --discard_variants %(NA)>0.1 --HDF --method "BurdenBt --name BurdenTest --alternative 2" --group_by refGene.name2 -j 10 --force -v 2
DEBUG: Using temporary directory /tmp/tmpek6917wr/_tmp_628095
DEBUG: Select phenotype and covariates using query SELECT sample_id, sample_name, smoking FROM sample LEFT OUTER JOIN filename ON sample.file_id = filename.file_id WHERE smoking IS NOT NULL
INFO: 2504 samples are found
DEBUG: Running query INSERT INTO __asso_tmp SELECT DISTINCT variant.variant_id, 0, refGene.refGene.name2  FROM variant, refGene.__rng_refGene_hg19_chr_txStart_txEnd, refGene.refGene WHERE (variant.bin = refGene.__rng_refGene_hg19_chr_txStart_txEnd.bin AND variant.chr = refGene.__rng_refGene_hg19_chr_txStart_txEnd.chr AND variant.pos >= refGene.__rng_refGene_hg19_chr_txStart_txEnd.start AND variant.pos <= refGene.__rng_refGene_hg19_chr_txStart_txEnd.end ) AND (refGene.refGene.rowid = refGene.__rng_refGene_hg19_chr_txStart_txEnd.range_id);
INFO: Grouping variants by 'refGene.name2', please be patient ...
INFO: 573 groups are found
Process GroupHDFGenerator-3:
Process GroupHDFGenerator-9:
Process GroupHDFGenerator-4:
Process GroupHDFGenerator-5:
Process GroupHDFGenerator-8:
Traceback (most recent call last):
  File "/home/mleong/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association_hdf5.py", line 78, in run
    for row in cur.execute(select_group):
Traceback (most recent call last):
vt_sqlite3.OperationalError: unable to open database file
  File "/home/mleong/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association_hdf5.py", line 78, in run
    for row in cur.execute(select_group):
Traceback (most recent call last):
vt_sqlite3.OperationalError: unable to open database file
  File "/home/mleong/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association_hdf5.py", line 78, in run
    for row in cur.execute(select_group):
Traceback (most recent call last):
vt_sqlite3.OperationalError: unable to open database file
  File "/home/mleong/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association_hdf5.py", line 78, in run
    for row in cur.execute(select_group):
vt_sqlite3.OperationalError: unable to open database file
Traceback (most recent call last):
  File "/home/mleong/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association_hdf5.py", line 78, in run
    for row in cur.execute(select_group):
vt_sqlite3.OperationalError: unable to open database file
^CTraceback (most recent call last):
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association.py", line 1202, in associate
    generateHDFbyGroup(asso,nJobs)
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association_hdf5.py", line 128, in generateHDFbyGroup
    groupHDFGenerator.join()
  File "/home/mleong/anaconda3/lib/python3.6/multiprocessing/process.py", line 121, in join
    res = self._popen.wait(timeout)
  File "/home/mleong/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 51, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/mleong/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```

ref:  #50

**Comment by HenryLeongStat** [comment]
For the test that I used `-j10` to import, the error messages show up when I use `-j10` to do the `association test`. However, it works OK when I use `-j4` to do the `association test`. 

<img width="1270" alt="screen shot 2017-11-06 at 2 30 32 pm" src="https://user-images.githubusercontent.com/26916551/32462476-14beef8c-c2ff-11e7-8f5c-4a76f9197a09.png">

**Comment by HenryLeongStat** [comment]
And I try to run `-j4` to do the `association test` again, the error shows up this time:

```
mleong@q1prpfs04:~/VariantTools/j10htestVarianttools$ vtools associate variant smoking --discard_variants "%(NA)>0.1" --HDF --method "BurdenBt --name BurdenTest --alternative 2" --group_by refGene.name2  -j 4 --force -v 2 > asso_test_j10_hdf5.log
DEBUG:
DEBUG: associate variant smoking --discard_variants %(NA)>0.1 --HDF --method "BurdenBt --name BurdenTest --alternative 2" --group_by refGene.name2 -j 4 --force -v 2
DEBUG: Using temporary directory /tmp/tmpsbdvovy5/_tmp_546906
DEBUG: Select phenotype and covariates using query SELECT sample_id, sample_name, smoking FROM sample LEFT OUTER JOIN filename ON sample.file_id = filename.file_id WHERE smoking IS NOT NULL
INFO: 2504 samples are found
DEBUG: Running query INSERT INTO __asso_tmp SELECT DISTINCT variant.variant_id, 0, refGene.refGene.name2  FROM variant, refGene.__rng_refGene_hg19_chr_txStart_txEnd, refGene.refGene WHERE (variant.bin = refGene.__rng_refGene_hg19_chr_txStart_txEnd.bin AND variant.chr = refGene.__rng_refGene_hg19_chr_txStart_txEnd.chr AND variant.pos >= refGene.__rng_refGene_hg19_chr_txStart_txEnd.start AND variant.pos <= refGene.__rng_refGene_hg19_chr_txStart_txEnd.end ) AND (refGene.refGene.rowid = refGene.__rng_refGene_hg19_chr_txStart_txEnd.range_id);
INFO: Grouping variants by 'refGene.name2', please be patient ...
INFO: 573 groups are found
Process GroupHDFGenerator-3:
Traceback (most recent call last):
  File "/home/mleong/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/mleong/anaconda3/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-linux-x86_64.egg/variant_tools/association_hdf5.py", line 78, in run
    for row in cur.execute(select_group):
vt_sqlite3.OperationalError: unable to open database file
```

It shows up randomly!?

**Comment by HenryLeongStat** [comment]
Fixed by Dr. Ma's patch [7d163e2](https://github.com/vatlab/VariantTools/commit/7d163e27deab193606532f7c7345e739185ba5c5).

Will keep testing for different number of jobs.
