### ISSUE TITLE
ValueError in Assotest

### ISSUE THREAD

**Issue by jma7** [vatlab/VariantTools#51]
While I was running association, I got an error message saying
```
    raise ValueError("No variant found in genotype data for {}.".format(repr(gname)))
TypeError: exceptions must derive from BaseException
```
Then I checked the type of ValueError, instead of deriving from build-in exception class, the ValueError here is from assoTests.py, and the ```Exception``` class is also from assoTests which gives error message:
```
Traceback (most recent call last):
  File "/Users/jma7/anaconda/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-macosx-10.7-x86_64.egg/variant_tools/association.py", line 1229, in associate
    runAssociation(args,asso,proj,results)
  File "/Users/jma7/anaconda/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-macosx-10.7-x86_64.egg/variant_tools/association.py", line 1144, in runAssociation
    except Exception as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
```  
@BoPeng

**Comment by BoPeng** [comment]
These exceptions are defined at the C++ level so that they can be raised to Python. I am checking the problem.

**Comment by BoPeng** [comment]
Pushed a fit but not sure if it works.

**Comment by jma7** [comment]
This is on V3 branch which already has these changes. The problem is still there. What is the purpose to define these exceptions again?

**Comment by BoPeng** [comment]
These are defined at the C++ level and once they are raised, they should be native Python exception. The problem here is that the exception is raised at the Python level but because we import everything from `assoTests`, the `Exception` class is imported and override the system `Exception`. I was trying not to define these in `assoTests` but it failed somehow.

My problem here is that I cannot reproduce the error without a sequence of commands to demonstrate the problem.

**Comment by jma7** [comment]
In the master branch, if you just do a keyboardInterrupt during running association, you will see the error message. 
```
Loading genotypes: 100% [========================================================================================] 2,504 143.7/s in 00:00:17
^CTraceback (most recent call last):
  File "/Users/jma7/anaconda/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-macosx-10.7-x86_64.egg/variant_tools/association.py", line 1110, in runAssociation
    time.sleep(random.random()*2)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jma7/anaconda/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-macosx-10.7-x86_64.egg/variant_tools/association.py", line 1230, in associate
    runAssociation(args,asso,proj,results)
  File "/Users/jma7/anaconda/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-macosx-10.7-x86_64.egg/variant_tools/association.py", line 1145, in runAssociation
    except Exception as e:
TypeError: catching classes that do not inherit from BaseException is not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jma7/anaconda/bin/vtools", line 11, in <module>
    load_entry_point('variant-tools==3.0.0.dev0', 'console_scripts', 'vtools')()
  File "/Users/jma7/anaconda/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-macosx-10.7-x86_64.egg/variant_tools/vtools.py", line 266, in main
    args.func(args)
  File "/Users/jma7/anaconda/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-macosx-10.7-x86_64.egg/variant_tools/association.py", line 1232, in associate
    except Exception as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
```
In some other functions if ```valueError``` is not from assoTest, it can be raised without error.

**Comment by BoPeng** [comment]
Then we will have to really avoid `import *` in that file.

**Comment by jma7** [comment]
Sorry, it seems the master branch is fine, the problem exists in the v3 branch.

**Comment by BoPeng** [comment]
I cannot reproduce this using sqlite backend and basic association test 

```
vtools init test --parent vt_ExomeAssociation
vtools use refGene
vtools associate rare status -m "CFisher --name Fisher --alternative 2" --group_by name2 --to_db cfisher -j8
```
I tried twice, once after genotype is imported, once after the association tests started.

Perhaps you were using hdf5 backend?

**Comment by jma7** [comment]
I just tried your example and I am getting the same error message after keyboardInterrupt after association started. Are you on V3 branch? Using hdf5 or sqlite doesn't matter in this case, the problem is the importing of AssoTest in association.py.

**Comment by BoPeng** [comment]
```
[bpeng1@bcbm-bpeng:~/vtools (v3)]$ git pull origin v3
From https://odin.mdacc.tmc.edu/jma7/VariantTools
 * branch            v3         -> FETCH_HEAD
Already up-to-date.
[bpeng1@bcbm-bpeng:~/vtools (v3)]$ vtools init test --parent vt_ExomeAssociation
ERROR: A project can only be created in a directory without another project.
[bpeng1@bcbm-bpeng:~/vtools (v3)]$ vtools use refGene
INFO: Choosing version refGene-hg19_20130904 from 5 available databases.
INFO: Downloading annotation database annoDB/refGene-hg19_20130904.ann
INFO: /Users/bpeng1/.variant_tools/annoDB/refGene-hg19_20130904.DB: MD5 signature mismatch, the database might have been upgraded locally.
INFO: Using annotation DB refGene as refGene in project test.
INFO: Known human protein-coding and non-protein-coding genes taken from the NCBI RNA reference sequences collection (RefSeq).
[bpeng1@bcbm-bpeng:~/vtools (v3)]$ vtools associate rare status -m "CFisher --name Fisher --alternative 2" --group_by name2 --to_db cfisher -j8
INFO: 3180 samples are found
INFO: 2681 groups are found
INFO: 46 out of 2681 groups with existing results are ignored. You can use option --force to re-analyze all groups.
INFO: Starting 8 processes to load genotypes
Loading genotypes: 100% [===============================================================================================] 3,180 24.3/s in 00:02:11
Testing for association:   4.1% [===>                                                                                   ] 108/8 13.5/s in 00:03:07^CERROR:
Association tests stopped by keyboard interruption (121/2635 completed).
refgene_name2	sample_size_Fisher	num_variants_Fisher	total_mac_Fisher	statistic_Fisher	pvalue_Fisher
NOTCH2NL     	3180              	2                  	12              	2.55191         	0.154628
LCE1F        	3100              	1                  	2               	0               	1
PADI2        	3180              	9                  	165             	0.757024        	0.380414
CPT2         	3180              	7                  	56              	0.912727        	1
DARS2        	3180              	2                  	18              	0.951975        	1
TBX15        	3180              	5                  	41              	0.821622        	1
MARS2        	3180              	1                  	1               	0               	1
RUSC1-AS1    	3162              	1                  	16              	1.77476         	0.418618
S100A7L2     	3180              	2                  	28              	0.913443        	1
GLI2         	3180              	8                  	87              	1.26073         	0.490244
SHCBP1L      	3180              	6                  	161             	1.18693         	0.444901
KLF7         	3180              	4                  	70              	0.720976        	0.569357
CYP2J2       	3180              	5                  	36              	0.445103        	0.427473
AMPD1        	3180              	5                  	125             	0.653022        	0.253089
CATIP        	3180              	2                  	31              	1.12998         	0.777028
MINOS1-NBL1  	3180              	4                  	27              	0.993585        	1
RAB10        	3180              	3                  	16              	1.08875         	0.707995
WBP1         	3180              	2                  	15              	1.17292         	0.690228
TRIM11       	3180              	3                  	20              	0.845595        	1
SPATA21      	3180              	6                  	64              	0.951312        	1
SLC44A5      	3180              	8                  	169             	0.762426        	0.380027
MRPL9        	3180              	6                  	101             	0.738859        	0.526264
TMEM53       	3180              	4                  	114             	0.911261        	0.880961
SPRR1A       	3180              	1                  	1               	0               	1
SAP130       	3180              	7                  	116             	0.337288        	0.0108602
MOB3C        	3180              	1                  	21              	0.800803        	1
TPO          	3180              	19                 	264             	1.02702         	0.918434
...
AHCYL1       	3180              	4                  	26              	0.632834        	0.760933
  ^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/bpeng1/anaconda/lib/python3.6/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt

```

**Comment by jma7** [comment]
```
(VariantTools) BSTMC07TP062G1J:VariantTools jma7$ git pull
Already up-to-date.
(VariantTools) BSTMC07TP062G1J:VariantTools jma7$ git branch
  geno_v3
  master
* v3
(VariantTools) BSTMC07TP062G1J:VariantTools jma7$ cd ../test
(VariantTools) BSTMC07TP062G1J:test jma7$ ls
build                      fib.c                      fib.pyx                    test.c                     test.log                   test.pyx
cfisher.DB                 fib.cpython-36m-darwin.so  setup.py                   test.cpython-36m-darwin.so test.proj                  test_genotype.DB
(VariantTools) BSTMC07TP062G1J:test jma7$ python setup.py install
running install
running build
running build_ext
building 'fib' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/jma7/anaconda/envs/VariantTools/include -arch x86_64 -I/Users/jma7/anaconda/envs/VariantTools/include -arch x86_64 -I/Users/jma7/anaconda/envs/VariantTools/include/python3.6m -c fib.c -o build/temp.macosx-10.7-x86_64-3.6/fib.o
creating build/lib.macosx-10.7-x86_64-3.6
gcc -bundle -undefined dynamic_lookup -L/Users/jma7/anaconda/envs/VariantTools/lib -L/Users/jma7/anaconda/envs/VariantTools/lib -arch x86_64 build/temp.macosx-10.7-x86_64-3.6/fib.o -L/Users/jma7/anaconda/envs/VariantTools/lib -o build/lib.macosx-10.7-x86_64-3.6/fib.cpython-36m-darwin.so
running install_lib
copying build/lib.macosx-10.7-x86_64-3.6/fib.cpython-36m-darwin.so -> /Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages
running install_egg_info
Writing /Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/UNKNOWN-0.0.0-py3.6.egg-info
(VariantTools) BSTMC07TP062G1J:test jma7$ vtools associate rare status -m "CFisher --name Fisher --alternative 2" --group_by name2 --to_db cfisher -j8
INFO: 3180 samples are found
INFO: 2681 groups are found
INFO: 30 out of 2681 groups with existing results are ignored. You can use option --force to re-analyze all groups.
INFO: Starting 8 processes to load genotypes
Loading genotypes:   3.9% [=====>                                                                                                                                        ] 124 12.6/s in 00:04:01^CERROR: 
Loading genotype stopped by keyboard interruption.
Process GenotypeLoader-1:
Traceback (most recent call last):
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-macosx-10.7-x86_64.egg/variant_tools/association.py", line 1051, in runAssociation
    time.sleep(random.random()*2)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-macosx-10.7-x86_64.egg/variant_tools/association.py", line 1070, in runAssociation
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-macosx-10.7-x86_64.egg/variant_tools/association.py", line 1226, in associate
    runAssociation(args,asso,proj,results)
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-macosx-10.7-x86_64.egg/variant_tools/association.py", line 1144, in runAssociation
    except Exception as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Comment by BoPeng** [comment]
You stopped at loading genotype, not association, perhaps this is the difference?

**Comment by BoPeng** [comment]
When I stop at the loading genotype stage, i got

```
$ vtools associate rare status -m "CFisher --name Fisher --alternative 2" --group_by name2 --to_db cfisher -j8
INFO: 3180 samples are found
INFO: 2681 groups are found
INFO: 167 out of 2681 groups with existing results are ignored. You can use option --force to re-analyze all groups.
Loading genotypes:   1.7% [=>                                                                                              ] 53 27.3/s in 00:01:54^CERROR:
Loading genotype stopped by keyboard interruption.
Process GenotypeLoader-8:
Process GenotypeLoader-1:
Process GenotypeLoader-4:
Process GenotypeLoader-2:
Process GenotypeLoader-6:
Process GenotypeLoader-7:
Traceback (most recent call last):
  File "/Users/bpeng1/anaconda/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/Users/bpeng1/anaconda/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-macosx-10.7-x86_64.egg/variant_tools/association.py", line 588, in run
    shelf.close()
  File "/Users/bpeng1/anaconda/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-macosx-10.7-x86_64.egg/variant_tools/utils.py", line 1607, in close
    raise ValueError('Temporary database {} does not exist.'.format(self.filename))
ValueError: Temporary database /var/folders/ys/gnzk0qbx5wbdgm531v82xxljv5yqy8/T/tmpxwplw_il/_tmp_494364/geno_7 does not exist.
Traceback (most recent call last):
  File "/Users/bpeng1/anaconda/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/Users/bpeng1/anaconda/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-macosx-10.7-x86_64.egg/variant_tools/association.py", line 588, in run
    shelf.close()
  File "/Users/bpeng1/anaconda/lib/python3.6/site-packages/variant_tools-3.0.0.dev0-py3.6-macosx-10.7-x86_64.egg/variant_tools/utils.py", line 1607, in close
    raise ValueError('Temporary database {} does not exist.'.format(self.filename))
Traceback (most recent call last):
```

**Comment by HenryLeongStat** [comment]
```
mleong@q1prpcfs05:/export/cfs05space/mleong/Cfisher$ vtools associate rare status -m "CFisher --name Fisher --alternative 2" --group_by name2 --to_db cfisher -j8
INFO: 3180 samples are found
INFO: 2681 groups are found
INFO: 1389 out of 2681 groups with existing results are ignored. You can use option --force to re-analyze all groups.
Loading genotypes: 100% [==================================================================================================================================] 3,180 76.1/s in 00:00:41
Testing for association:  14.9% [================>                                                                                                        ] 192/10 37.6/s in 00:00:29refgene_name2  	sample_size_Fisher	num_variants_Fisher	total_mac_Fisher	statistic_Fisher	pvalue_Fisher
MTHFR          	3180              	10                 	124             	1.15666         	0.564877
SDHB           	3180              	2                  	42              	1.57938         	0.319876
TMCC2          	3180              	2                  	25              	1.03912         	1
YIPF1          	3180              	2                  	18              	1.52787         	0.456392
RNF103         	3180              	5                  	87              	0.571608        	0.229313
METAP1D        	3180              	6                  	154             	1.03258         	0.896318
ODC1           	3180              	8                  	64              	1.13143         	0.689686
RNF220         	3180              	9                  	105             	0.918411        	1
OR2L13         	3180              	23                 	217             	1.4528          	0.0739833
MIR6734        	3170              	1                  	1               	1.79769E+308    	0.116088
PRUNE          	3180              	3                  	42              	0.582598        	0.472431
TPR            	3180              	2                  	76              	0.768436        	0.715668
RAMP1          	3180              	2                  	19              	0               	0.155592
VIT            	3180              	12                 	144             	0.902946        	0.789197
RSC1A1         	3180              	5                  	41              	0.193144        	0.0799452
SPRTN          	3171              	1                  	3               	0               	1
TMEM63A        	3180              	11                 	107             	1.28107         	0.354551
SGIP1          	3180              	7                  	104             	2.03384         	0.00701306
OR10Z1         	3180              	2                  	21              	0               	0.161505
PLEKHN1        	3180              	5                  	153             	1.21111         	0.428825
WDTC1          	3180              	4                  	21              	2.39955         	0.087147
SCTR           	3180              	11                 	247             	1.00664         	1
PYHIN1         	3180              	4                  	66              	0.770976        	0.696068
SNX7           	3180              	3                  	76              	0.893922        	1
PPIG           	3180              	2                  	3               	0               	1
RABL2A         	3180              	4                  	63              	1.66283         	0.156348
MTX2           	3180              	4                  	41              	1.57938         	0.319876
OVGP1          	3180              	8                  	64              	1.09023         	0.842882
PLEKHB2        	3180              	5                  	68              	0.871751        	0.849921
SGPP2          	3180              	4                  	66              	0.770976        	0.696068
PDPN           	3180              	4                  	65              	0.770976        	0.696068
RAB4A          	3180              	1                  	1               	1.79769E+308    	0.116038
...
ZNF644         	3180              	8                  	129             	1.03069         	0.88717
^CERROR:
Association tests stopped by keyboard interruption (248/1292 completed).
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/mleong/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```

**Comment by jma7** [comment]
The problem has fixed on gitlab v3 branch.
