### ISSUE TITLE
Install variantTools from main branch, when run "vtools" got error message. 

### ISSUE THREAD

**Issue by BingLi17** [vatlab/VariantTools#64]
```
Traceback (most recent call last):
  File "/anaconda3/bin/vtools", line 52, in <module>
    import variant_tools.association as association
  File "/anaconda3/lib/python3.6/site-packages/variant_tools/association.py", line 36, in <module>
    from .tester import *
  File "/anaconda3/lib/python3.6/site-packages/variant_tools/tester.py", line 32, in <module>
    from . import assoTests as t
  File "/anaconda3/lib/python3.6/site-packages/variant_tools/assoTests.py", line 30, in <module>
    _assoTests = swig_import_helper()
  File "/anaconda3/lib/python3.6/site-packages/variant_tools/assoTests.py", line 26, in swig_import_helper
    _mod = imp.load_module('_assoTests', fp, pathname, description)
  File "/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/anaconda3/lib/python3.6/site-packages/variant_tools/_assoTests.cpython-36m-darwin.so, 2): Symbol not found: _cblas_caxp
```

**Comment by BoPeng** [comment]
This should be related to [this line of code in setup.py](https://github.com/vatlab/VariantTools/blob/master/setup.py#L777). We removed `blas` library because it caused troubles under some linux systems and the resulting variant tools seems to work fine. Could you check if variant tools works if you include this library?

**Comment by BingLi17** [comment]
It works now!

**Comment by BoPeng** [comment]
Then the safe way is to require this library despite the fact that it is unavailable and actually not used on some systems...

@tutudong : please update setup.py to include this library. Remember to refer to this ticket in your commit.
