### ISSUE TITLE
Index out of range error after expanding snapshot

### ISSUE THREAD

**Issue by BoPeng** [vatlab/VariantTools#94]
```
s$ vtools init test -f --parent vt_ExomeAssociation 
INFO: variant tools 3.0.1 : Copyright (c) 2011 - 2016 Bo Peng
INFO: Please visit http://varianttools.sourceforge.net for more information.
INFO: Creating a new project test
INFO: Extracting snapshot vt_ExomeAssociation to .
Downloading snapshot vt_ExomeAssociation.tar.gz from online repository
Extracting vt_ExomeAssociation:  97.6% [============================================================================================================================================================================>     ] 436,040,955 54.3M/s in 00:00:00Current storage mode is HDF5, transfrom genotype storage mode.....
Creating indexes: 100% [=========================================================================================================================================================================================================] 3,180 32.8/s in 00:01:36
Selecting genotypes: 100% [=========================================================================================================================================================================================================] 53 16.8/s in 00:00:03
Getting existing variants: 100% [=============================================================================================================================================================================================] 26,797 507.3K/s in 00:00:00
list index out of range
ERROR: Failed to load snapshot: list index out of range

```

@jma7 Can you reproduce this? I am running on a Linux system with trunk of variant tools.

**Comment by BoPeng** [comment]
```
  File "/Users/bpeng1/vtools/src/variant_tools/project.py", line 4393, in init
    parent_proj.loadSnapshot(parent_snapshot)
Traceback (most recent call last):
  File "/Users/bpeng1/vtools/src/variant_tools/project.py", line 2890, in loadSnapshot
    all_files = store.load_Genotype_From_SQLite(all_files, self)
  File "/Users/bpeng1/vtools/src/variant_tools/geno_store.py", line 1187, in load_Genotype_From_SQLite
    IDs,0, job, HDFfile_Merge,validGenotypeFields, self.proj.build))
  File "/Users/bpeng1/vtools/src/variant_tools/importer_allele_hdf5.py", line 1019, in __init__
    self.colnames=[self.sample_ids[i] for i in range(self.start_sample,self.end_sample)]
  File "/Users/bpeng1/vtools/src/variant_tools/importer_allele_hdf5.py", line 1019, in <listcomp>
    self.colnames=[self.sample_ids[i] for i in range(self.start_sample,self.end_sample)]
IndexError: list index out of range
```

**Comment by BoPeng** [comment]
@jma7 Can you reproduce this? I am going to release 3.0.1 with fix for #88

**Comment by jma7** [comment]
Just tried, I got the same error, will take a look at it.

**Comment by BoPeng** [comment]
Thanks. This looks like an indexing error for HDF5...

**Comment by BoPeng** [comment]
Confirm fixed.
